#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=30

start() {
	LED=0
	SM=$(uci get system.led_wlan2g)
	if [ -z $SM ]; then
		uci set system.led_wlan2g=led
		uci set system.led_wlan2g.name="WLAN2G"
		uci set system.led_wlan2g.sysfs="wifi0"
		uci set system.led_wlan2g.trigger="netdev"
		uci set system.led_wlan2g.dev="phy0-ap0"
		uci set system.led_wlan2g.mode="link tx rx"
		
		uci set system.led_wlan5g=led
		uci set system.led_wlan5g.name="WLAN2G"
		uci set system.led_wlan5g.sysfs="wifi1"
		uci set system.led_wlan5g.trigger="netdev"
		uci set system.led_wlan5g.dev="phy1-ap0"
		uci set system.led_wlan5g.mode="link tx rx"

		uci commit system
		/etc/init.d/led restart
		cp /etc/luci-base.json /usr/share/luci/menu.d
	fi
	source /etc/openwrt_release
	rm -f /etc/openwrt_release

	DISTRIB_DESCRIPTION="GoldenOrb"
	DISTRIB_REVISION=" "

	echo "$(uci get modem.Version.ver)" > /etc/revision
	echo 'DISTRIB_ID="'"$DISTRIB_ID"'"' >> /etc/openwrt_release
	echo 'DISTRIB_RELEASE="'"$DISTRIB_RELEASE"'"' >> /etc/openwrt_release
	echo 'DISTRIB_REVISION="'"$DISTRIB_REVISION"'"' >> /etc/openwrt_release
	echo 'DISTRIB_CODENAME="'"$DISTRIB_CODENAME"'"' >> /etc/openwrt_release
	echo 'DISTRIB_TARGET="'"$DISTRIB_TARGET"'"' >> /etc/openwrt_release
	echo 'DISTRIB_DESCRIPTION="'"$DISTRIB_DESCRIPTION"'"' >> /etc/openwrt_release
}
